version: '3.7'

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-cpp-ce:latest
    container_name: artifactory
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - artifactory-data:/var/opt/jfrog/artifactory
    restart: always

volumes:
  artifactory-volume:
    name: artifactory-data